services:
  - type: web
    name: subscription-service
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn subscription_service.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: subscription_db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

databases:
  - name: subscription_db
    databaseName: subscription
    user: subscription_user 